services:
    mariadb_main:
        image: mariadb:10.11.6-jammy
        container_name: teamup-main-db
        restart: unless-stopped
        ports:
          - 3306:3306
        environment:
          TZ: Asia/Seoul
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_USER: ${MAIN_MYSQL_USER}
          MYSQL_PASSWORD: ${MAIN_MYSQL_PASSWORD}
          MYSQL_DATABASE: ${MAIN_MYSQL_DATABASE}
        volumes:
          - ./mariadb-main-mount/var-lib-mysql:/var/lib/mysql
          - ./mariadb-main-mount/config:/etc/mysql/conf.d
          - ./mariadb-main-mount/initdb.d/V000_INIT_DB.sql:/docker-entrypoint-initdb.d/V000_INIT_DB.sql
        command:
          - --character-set-server=utf8mb4
          - --collation-server=utf8mb4_unicode_ci

    mariadb_test:
        image: mariadb:10.11.6-jammy
        container_name: teamup-test-db
        restart: unless-stopped
        ports:
          - 3307:3306
        environment:
          TZ: Asia/Seoul
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_USER: ${TEST_MYSQL_USER}
          MYSQL_PASSWORD: ${TEST_MYSQL_PASSWORD}
          MYSQL_DATABASE: ${TEST_MYSQL_DATABASE}
        volumes:
          - ./mariadb-test-mount/var-lib-mysql:/var/lib/mysql
          - ./mariadb-test-mount/config:/etc/mysql/conf.d
          - ./mariadb-test-mount/initdb.d/V000_INIT_DB.sql:/docker-entrypoint-initdb.d/V000_INIT_DB.sql
        command:
          - --character-set-server=utf8mb4
          - --collation-server=utf8mb4_unicode_ci

    redis_main:  
        image: redis:7.0.15
        container_name: teamup-main-redis
        ports:
          - 6379:6379
        command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--requirepass", "${MAIN_REDIS_PASSWORD}"]
        volumes:
          - ./redis-main-mount/data:/data
          - ./redis-main-mount/conf/redis.conf:/usr/local/etc/redis/redis.conf