services:
    mariadb:
        image: mariadb:10.11.6-jammy
        container_name: teamup-main-db
        restart: unless-stopped
        ports:
          - 3306:3306
        environment:
          TZ: Asia/Seoul
        volumes:
          - ./mariadb-mount/var-lib-mysql:/var/lib/mysql
          - ./mariadb-mount/config:/etc/mysql/conf.d
          - ./mariadb-mount/initdb.d/V000_INIT_DB.sql:/docker-entrypoint-initdb.d/V000_INIT_DB.sql
        env_file: .env
        command:
          - --character-set-server=utf8mb4
          - --collation-server=utf8mb4_unicode_ci
    redis:  
        image: redis:7.0.15
        container_name: teamup-redis
        ports:
          - 6379:6379
        env_file: .env
        command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--requirepass", "${REDIS_PASSWORD}"]
        volumes:
          - ./redis-mount/data:/data
          - ./redis-mount/conf/redis.conf:/usr/local/etc/redis/redis.conf