CREATE DATABASE IF NOT EXISTS teamup 
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

GRANT ALL PRIVILEGES ON teamup.* TO 'DB_USER_ID_MODIFY'@'%' IDENTIFIED BY 'DB_USER_PASSWORD_MODIFY' WITH GRANT OPTION;
FLUSH PRIVILEGES;
