USE teamup;

CREATE TABLE IF NOT EXISTS `RESUME` (
	`IDX` BIGINT AUTO_INCREMENT NOT NULL,
	`INTRODUCTION` TEXT NOT NULL,
	`PROJECT_URL` TEXT NOT NULL,
	`SKILL` TEXT NOT NULL,
	`EXPERIENCE` TEXT NOT NULL,
	`ADDITIONAL_INFO` TEXT NOT NULL,
	CERTIFICATE varchar(1000) NOT NULL,
	CONSTRAINT `RESUME_PK` PRIMARY KEY (`IDX`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS `RESUME_LANGUAGE` (
	`IDX` BIGINT AUTO_INCREMENT NOT NULL,
	`RESUME_IDX` BIGINT NOT NULL,
	`TYPE` varchar(50) NOT NULL,
	`GRADE` TINYINT(1) NOT NULL,
	CONSTRAINT `RESUME_LANGUAGE_PK` PRIMARY KEY (`IDX`),
	CONSTRAINT `RESUME_LANGUAGE_RESUME_FK` FOREIGN KEY (`RESUME_IDX`) REFERENCES `RESUME` (`IDX`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `RESUME` ADD `USER_IDX` BIGINT NOT NULL;
ALTER TABLE `RESUME` ADD CONSTRAINT `RESUME_USERS_FK` FOREIGN KEY (`USER_IDX`) REFERENCES `USERS` (`IDX`);
